Vagrant.configure("2") do |config|
  config.vm.define "ubuntu_vm" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"
    ubuntu.vm.hostname = "container101-ubuntu"
    ubuntu.vm.provider "virtualbox" do |ub|
      ub.memory = "2048"
      ub.cpus = 2
    end
    ubuntu.vm.network "public_network", ip: "192.168.10.10"
    ubuntu.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin net-tools bridge-utils
      sudo systemctl enable --now docker
      sudo sysctl net.bridge.bridge-nf-call-iptables=0
      sudo sysctl net.bridge.bridge-nf-call-ip6tables=0
    SHELL
  end
  config.vm.define "centos_vm" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.hostname = "container101-centos8"
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    centos.vm.network "public_network", ip: "192.168.10.5"
    centos.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y yum-utils
      sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      sudo systemctl start docker
      sudo systemctl enable docker
    SHELL
  end
end
