apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-nginx-access
  namespace: test-nginx
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: test-np
      podSelector:
        matchLabels:
          nginx-np: "true"
    ports:
    - protocol: TCP
      port: 80
