apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "group1"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
