Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    
    # Set the hostname
    config.vm.hostname = "container101"
    
    # Configure the VM with 2 CPUs and 4GB of memory
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    
    # Add a 100GB disk
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["createhd", "--filename", "disk.vdi", "--size", 100 * 1024]
      vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "disk.vdi"]
    end
  # Install Docker
    config.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y yum-utils
      sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      sudo systemctl start docker
      sudo systemctl enable docker
    SHELL
  end