apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-intro-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: k8s-intro-nginx
        image: quay.io/emre_celik/k8s-intro-nginx
        ports:
        - containerPort: 80
