Vagrant.configure("2") do |config|
  config.vm.define "ubuntu_vm" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"
    ubuntu.vm.hostname = "container101-ubuntu"
    ubuntu.vm.provider "virtualbox" do |ub|
      ub.memory = "4096"
      ub.cpus = 4
    end
    ubuntu.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin net-tools bridge-utils apt-transport-https ca-certificates curl
      sudo systemctl enable --now docker
      sudo sysctl net.bridge.bridge-nf-call-iptables=0
      sudo sysctl net.bridge.bridge-nf-call-ip6tables=0
      sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      sudo install minikube-linux-amd64 /usr/local/bin/minikube
      sudo curl -LO "https://dl.k8s.io/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      sudo usermod -aG docker $USER && newgrp docker
      minikube start --driver=docker
    SHELL
  end
end
